nums = list(map(int, input().split()))
count = len(nums)
_sum = sum(nums)
_min = min(nums)
_max = max(nums)
mean = _sum / count
evens = sum(1 for x in nums if x % 2 == 0)
odds = sum(1 for x in nums if x % 2 != 0)
print(f"count: {count}")
print(f"sum: {_sum}")
print(f"min: {_min}")
print(f"max: {_max}")
print(f"mean: {mean:.2f}")
print(f"evens: {evens}")
print(f"odds: {odds}")